// Code generated by hertz generator.

package user

import (
	"context"

	user "hertz/biz/model/user"
	"hertz/database"
	"hertz/pkg/repository"
	"hertz/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// @Summary      用户注册
// @Description  用户通过账号和密码创建新用户
// @Tags			 User
// @Produce      json
// @param username body string true "用户名"
// @param password body string true "密码"
// @Success      200  {string}  bool "注册成功"
// @Failure      500  {string}  bool "注册失败"
// @Router       /register [post]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	us := service.NewUserService(repository.NewUserRepository(database.GetMysql()))

	if us.Register(req.Username, req.Password) {
		c.JSON(consts.StatusCreated, &user.Response{
			Status: 404,
			Msg:    "注册失败",
		})
		return
	}

	c.JSON(consts.StatusOK, &user.Response{
		Status: 200,
		Msg:    "注册成功",
	})
}
