// Code generated by hertz generator.

package main

import (
	"log"
	"memogo/biz/dal/db"
	"memogo/biz/dal/redis"
	"memogo/pkg/middleware"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/swagger"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
)

func main() {
	// 加载 .env 文件（如果存在）
	if err := godotenv.Load(); err != nil {
		log.Println("Warning: .env file not found, using environment variables or defaults")
	}

	// 初始化数据库
	db.Init()

	// 初始化 Redis（可选，如果连接失败会降级到无缓存模式）
	redis.Init()

	// 初始化 JWT 中间件
	var err error
	middleware.JWTMiddleware, err = middleware.InitJWTMiddleware()
	if err != nil {
		log.Fatal("Failed to initialize JWT middleware: ", err)
	}

	h := server.Default(server.WithHostPorts(":8888"))

	// 注册业务路由
	register(h)

	// 注册 Swagger 文档路由（使用本地 openapi.json）
	url := swagger.URL("http://localhost:8888/docs/openapi.json")
	h.GET("/docs/*any", swagger.WrapHandler(swaggerFiles.Handler, url))

	// 提供 openapi.json 文件
	h.StaticFile("/docs/openapi.json", "./docs/openapi.json")

	log.Println("📖 API 文档地址: http://localhost:8888/docs/index.html")
	log.Println("📡 API 服务地址: http://localhost:8888")

	h.Spin()
}
