// Code generated by hertz generator.

package main

import (
    "github.com/cloudwego/hertz/pkg/app/server"
    handler "memogo/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
    r.GET("/ping", handler.Ping)

    // 自定义路由可以在这里添加
    // 说明：IDL 已使用 `:id` 语法，生成的路由可直接工作，无需额外别名
}
