// Code generated by hertz generator.

package main

import (
	"hertz/config"
	"hertz/database"
	"hertz/pkg/middleware"
	"hertz/pkg/repository"
	"hertz/pkg/service"

	_ "hertz/docs"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
)

// @title           Hertz Todo API
// @version         1.0
// @description     A simple Todo app with Hertz + JWT + GORM
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey Bearer
// @in              header
// @name            Authorization
// @description     Type "Bearer" followed by a space and JWT token.
func main() {
	cfg := config.GetConfig()
	h := server.Default(server.WithHostPorts(":" + cfg.Server.Port))
	h.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler))
	h.POST("/login", middleware.NewJWTMiddleware(service.NewUserService(repository.NewUserRepository(database.GetMysql()))).LoginHandler)
	register(h)
	h.Spin()
}
