// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	task "github.com/west2-online-reserve/collection-golang/work3/biz/router/task"
	user "github.com/west2-online-reserve/collection-golang/work3/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	task.Register(r)

	user.Register(r)

}
