// Code generated by hertz generator.

package todo

import (
	"hertz/database"
	"hertz/pkg/middleware"
	"hertz/pkg/repository"
	"hertz/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	auth := middleware.NewJWTMiddleware(service.NewUserService(repository.NewUserRepository(database.GetMysql())))
	return []app.HandlerFunc{auth.MiddlewareFunc()}
}

func _addtodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _finishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settodofinishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettodosfinishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settodosfinishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _keyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getkeytodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _notfinishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settodonotfinishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettodosnotfinishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settodosnotfinishedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletefinishedtodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletenotfinishedtodosMw() []app.HandlerFunc {
	// your code...
	return nil
}
