package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math/rand"

	"github.com/gocolly/colly"
)

type AutoGenerated struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	TTL     int    `json:"ttl"`
	Data    struct {
		Replies []struct {
			Member struct {
				Mid   string `json:"mid"`
				Uname string `json:"uname"`
				Sex   string `json:"sex"`
			} `json:"member"`
			Content struct {
				Message string        `json:"message"`
				Members []interface{} `json:"members"`
				MaxLine int           `json:"max_line"`
			} `json:"content,omitempty"`
			ReplyControl struct {
				MaxLine           int    `json:"max_line"`
				SubReplyEntryText string `json:"sub_reply_entry_text"`
				SubReplyTitleText string `json:"sub_reply_title_text"`
				TimeDesc          string `json:"time_desc"`
			} `json:"reply_control,omitempty"`
		} `json:"replies"`
	} `json:"data"`
}

const letterBytes = "qwertyuioplkjhgfdsazxcvbnmQWERTYUIOPLKJHGFDSAZXCVBNM"

func RandomString() string {
	b := make([]byte, rand.Intn(10)+10)
	for i := range b {
		b[i] = letterBytes[rand.Intn(len(letterBytes))]
	}
	return string(b)
}
func main() {
	c := colly.NewCollector()
	c.OnRequest(func(req *colly.Request) {
		req.Headers.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0")
		req.Headers.Set("Sec-Ch-Ua-Platform", `"Windows"`)
		req.Headers.Set("Origin", "https://www.bilibili.com")
		req.Headers.Set("Cookie", "buvid3=DCB25747-EC5E-6BB2-D242-943AF7EDA86A62426infoc; b_nut=100; _uuid=28F7FEBA-9910B-845D-7179-7B79E4E8BEAC62971infoc; buvid4=C84632D9-402D-38A0-F908-AFB5A1F784D763579-023081700-nUpjx%2FRbFQM9NuUWnMOYmg%3D%3D; DedeUserID=1525270090; DedeUserID__ckMd5=902615919c3c177f; rpdid=|(J~|R|mR~)k0J'uYmkk|kmu~; is-2022-channel=1; CURRENT_BLACKGAP=0; CURRENT_FNVAL=4048; fingerprint=13fd563ba306d487b855ad2b8afc1889; buvid_fp_plain=undefined; LIVE_BUVID=AUTO2916947865719986; buvid_fp=13fd563ba306d487b855ad2b8afc1889; home_feed_column=5; browser_resolution=1488-742; CURRENT_QUALITY=64; enable_web_push=DISABLE; header_theme_version=CLOSE; SESSDATA=2ad8bad5%2C1714715069%2C36099%2Ab2CjBKO8T0R46N1Tx4yt313SsO1UCAae6h0p8lxT2aHlsnbo75cHp7VpbifOvHqW9-_IYSVlE4VUtDV0YtZGRCTXNlNGEyZFBwaWkzbUZaVmhXaWYxcEZFZTh4bU9uRC1UU0lyVmNXRWtMTndZUzkyT3YtMHphR1VmVHUyVFplRjJYMUFrRzFnc3VnIIEC; bili_jct=3d4c0c48c33f29f25ec8c6668902aac3; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk0MjIyNzIsImlhdCI6MTY5OTE2MzAxMiwicGx0IjotMX0.B3aHyjOouxvCyql-O4yeo4flVggF5iBzw_KxSSUT41I; bili_ticket_expires=1699422212; PVID=1; sid=7pvei21u; b_lsid=3CFDA1039_18BAA2B2A75; bp_video_offset_1525270090=861255395171106836")
		req.Headers.Set("Accept-Language", "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6")
		req.Headers.Set("Referer", "https://www.bilibili.com/vi")
		req.Headers.Set("authority", "api.bilibili.com")
		req.Headers.Set("Accept", "*/*")
		req.Headers.Set("Sec-Ch-Ua", `"Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"`)
		req.Headers.Set("Sec-Ch-Ua-Mobile", "?0")
		req.Headers.Set("Sec-Fetch-Dest", "empty")
		req.Headers.Set("Sec-Fetch-Mode", "cors")
		req.Headers.Set("Sec-Fetch-Site:", "same-site")
		req.Headers.Set("User-Agent", "RandomString")
	})
	containner := AutoGenerated{}
	c.OnResponse(func(r *colly.Response) {
		fmt.Println(r.StatusCode)
		err := json.Unmarshal(r.Body, &containner)
		if err != nil {
			fmt.Println(err)
			log.Fatal(err)
		}

	})
	c.Visit("https://api.bilibili.com/x/v2/reply/wbi/main?oid=420981979&type=1&mode=3&pagination_str=%7B%22offset%22:%22%7B%5C%22type%5C%22:1,%5C%22direction%5C%22:1,%5C%22session_id%5C%22:%5C%221740207251991296%5C%22,%5C%22data%5C%22:%7B%7D%7D%22%7D&plat=1&web_location=1315875&w_rid=7b6a3311226bb32a3247a385cccec267&wts=1699421180")
	for i, reply := range containner.Data.Replies {
		fmt.Println(i, reply.Member.Uname, reply.Content.Message, reply.ReplyControl.TimeDesc)
	}

}
