// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/west2-online-reserve/collection-golang/work3/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.AuthToken(),
	}
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskbystatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytasklistbykeywordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querytasklistbystatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}
