// Code generated by hertz generator.

package api

import (
	"context"
	"errors"
	"memogo/biz/dal/db"
	"memogo/biz/dal/repository"
	"memogo/biz/model/memogo/api"
	"memogo/biz/service"
	"memogo/pkg/middleware"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /v1/auth/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 创建 service
	userRepo := repository.NewUserRepository(db.DB)
	authService := service.NewAuthService(userRepo)

	// 调用注册服务
	accessToken, refreshToken, err := authService.Register(req.Username, req.Password)
	if err != nil {
		// 根据不同错误返回不同状态码
		if errors.Is(err, repository.ErrUserAlreadyExists) {
			c.JSON(consts.StatusBadRequest, &api.AuthResp{
				Status: 400,
				Msg:    "Username already exists",
			})
			return
		}
		c.JSON(consts.StatusInternalServerError, &api.AuthResp{
			Status: 500,
			Msg:    "Registration failed: " + err.Error(),
		})
		return
	}

	resp := &api.AuthResp{
		Status: 200,
		Msg:    "Registration successful",
		Data: &api.TokenPair{
			AccessToken:  accessToken,
			RefreshToken: refreshToken,
		},
	}

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /v1/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	// 使用 Hertz JWT 中间件的 LoginHandler
	middleware.JWTMiddleware.LoginHandler(ctx, c)
}

// RefreshToken .
// @router /v1/auth/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	// 使用 Hertz JWT 中间件的 RefreshHandler
	middleware.JWTMiddleware.RefreshHandler(ctx, c)
}

// CreateTodo .
// @router /v1/todos [POST]
func CreateTodo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateTodoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 从 JWT 中间件获取用户 ID
	userID, err := middleware.GetUserID(c)
	if err != nil {
		c.JSON(consts.StatusUnauthorized, &api.CreateTodoResp{
			Status: 401,
			Msg:    "Unauthorized: " + err.Error(),
		})
		return
	}

	// TODO: 使用 userID 创建 todo
	// 这里只是演示如何获取用户信息
	// 临时返回，演示获取到的用户ID
	c.String(consts.StatusOK, "User ID: %d, Title: %s", userID, req.Title)
}

// UpdateTodoStatus .
// @router /v1/todos/{id}/status [PATCH]
func UpdateTodoStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateTodoStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateTodoStatusResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateAllStatus .
// @router /v1/todos/status [PATCH]
func UpdateAllStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateAllStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateAllStatusResp)

	c.JSON(consts.StatusOK, resp)
}

// ListTodos .
// @router /v1/todos [GET]
func ListTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListTodosReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ListTodosResp)

	c.JSON(consts.StatusOK, resp)
}

// SearchTodos .
// @router /v1/todos/search [GET]
func SearchTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchTodosReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.SearchTodosResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteOne .
// @router /v1/todos/{id} [DELETE]
func DeleteOne(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteOneReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteByScope .
// @router /v1/todos [DELETE]
func DeleteByScope(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteByScopeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteResp)

	c.JSON(consts.StatusOK, resp)
}
