// Code generated by hertz generator.

package api

import (
	"context"
	"memogo/biz/model/memogo/api"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /v1/auth/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.AuthResp)

	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /v1/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.AuthResp)

	c.JSON(consts.StatusOK, resp)
}

// RefreshToken .
// @router /v1/auth/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RefreshReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.AuthResp)

	c.JSON(consts.StatusOK, resp)
}

// CreateTodo .
// @router /v1/todos [POST]
func CreateTodo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CreateTodoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.CreateTodoResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateTodoStatus .
// @router /v1/todos/{id}/status [PATCH]
func UpdateTodoStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateTodoStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateTodoStatusResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateAllStatus .
// @router /v1/todos/status [PATCH]
func UpdateAllStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UpdateAllStatusReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.UpdateAllStatusResp)

	c.JSON(consts.StatusOK, resp)
}

// ListTodos .
// @router /v1/todos [GET]
func ListTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListTodosReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ListTodosResp)

	c.JSON(consts.StatusOK, resp)
}

// SearchTodos .
// @router /v1/todos/search [GET]
func SearchTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchTodosReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.SearchTodosResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteOne .
// @router /v1/todos/{id} [DELETE]
func DeleteOne(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteOneReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteByScope .
// @router /v1/todos [DELETE]
func DeleteByScope(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.DeleteByScopeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.DeleteResp)

	c.JSON(consts.StatusOK, resp)
}
