// Code generated by hertz generator.

package todo

import (
	"context"
	"time"

	todo "hertz/biz/model/todo"
	"hertz/database"
	"hertz/pkg/model"
	"hertz/pkg/repository"
	"hertz/pkg/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// @Summary      添加代办
// @Description  用户添加一个代办事件
// @Tags		 Todo
// @Produce      json
// @Param		 username body string true "用户名"
// @Param 		 password body string true "密码"
// @Success      201  {string}  bool "添加成功"
// @Failure      500  {string}  bool "添加失败"
// @Security     Bearer
// @Router       /auto/todo [post]
func AddTodo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.AddRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	startTime, _ := time.Parse(time.RFC3339, req.Todo.StartTime)
	endTime, _ := time.Parse(time.RFC3339, req.Todo.EndTime)
	if ts.AddTodo(&model.Todo{
		Uid:       uid.(uint64),
		Title:     req.Todo.Title,
		Content:   req.Todo.Content,
		View:      0,
		Status:    0,
		CreatedAt: time.Now(),
		StartTime: startTime,
		EndTime:   endTime,
	}) {
		c.JSON(consts.StatusCreated, &todo.Response{
			Status: 201,
			Msg:    "创建成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "服务器错误",
	})
}

// @Summary      完成一个代办
// @Description  用户设置一个代办事件为完成状态
// @Tags		 Todo
// @Produce      json
// @param 		 id path uint64 true "代办id"
// @Success      201  {string}  bool "设置成功"
// @Failure      500  {string}  bool "设置失败"
// @Router       /auth/finished/todo [put]
func SetTodoFinished(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.SetTodoFinishedRequest
	err = c.BindAndValidate(&req)
	if err != nil || req.Id == 0 {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.SetTodoFinishedById(uid.(uint64), req.Id) {
		c.JSON(consts.StatusCreated, &todo.Response{
			Status: 201,
			Msg:    "修改成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "服务器错误",
	})
}

// @Summary      完成全部代办
// @Description  用户设置全部代办事件为完成状态
// @Tags		 Todo
// @Produce      json
// @Success      201  {string}  bool "设置成功"
// @Failure      500  {string}  bool "设置失败"
// @Router       /auth/finished/todos [put]
func SetTodosFinished(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.SetTodosFinishedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.SetTodosFinished(uid.(uint64)) {
		c.JSON(consts.StatusCreated, &todo.Response{
			Status: 201,
			Msg:    "修改成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "服务器错误",
	})
}

// @Summary      取消完成一个代办
// @Description  用户设置一个代办事件为未完成状态
// @Tags		 Todo
// @Produce      json
// @Param 		 id path uint64 true "代办id"
// @Success      201  {string}  bool "设置成功"
// @Failure      500  {string}  bool "设置失败"
// @Router       /auth/notfinished/todo [put]
func SetTodoNotFinished(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.SetTodoNotFinishedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.SetTodoNotFinishedById(uid.(uint64), req.Id) {
		c.JSON(consts.StatusCreated, &todo.Response{
			Status: 201,
			Msg:    "修改成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "服务器错误",
	})
}

// @Summary      未完成全部代办
// @Description  用户设置全部代办事件为未完成状态
// @Tags		 Todo
// @Produce      json
// @Success      201  {string}  bool "设置成功"
// @Failure      500  {string}  bool "设置失败"
// @Router       /auth/notfinished/todos [put]
func SetTodosNotFinished(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.SetTodosNotFinishedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.SetTodosNotFinished(uid.(uint64)) {
		c.JSON(consts.StatusCreated, &todo.Response{
			Status: 201,
			Msg:    "修改成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "服务器错误",
	})
}

// @Summary      获取全部代办
// @Description  用户获取他的全部代办事件
// @Tags		 Todo
// @Produce      json
// @Success      200  {object} 	[]interface{} "返回代办信息"
// @Failure      500  {string}  bool "获取失败"
// @Router       /auth/todos [get]
func GetTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.GetTodosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.TodoResponse{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	todos, total := ts.GetTodos(uid.(uint64), int(req.PageNum), int(req.PageSize))
	var todoMaps []*todo.Todo
	for _, t := range todos {
		todoMaps = append(todoMaps, &todo.Todo{
			Id:        t.ID,
			Title:     t.Title,
			Content:   t.Content,
			View:      t.View,
			Status:    uint32(t.Status),
			CreatedAt: t.CreatedAt.Format(time.RFC3339),
			StartTime: t.StartTime.Format(time.RFC3339),
			EndTime:   t.EndTime.Format(time.RFC3339),
		})
	}

	c.JSON(consts.StatusCreated, &todo.TodoResponse{
		Status: 201,
		Msg:    "获取成功",
		Data: &todo.TodoList{
			Items: todoMaps,
			Total: total,
		},
	})
}

// @Summary      获取全部完成代办
// @Description  用户获取他的全部完成代办事件
// @Tags		 Todo
// @Produce      json
// @Success      200  {object}  []interface{} "返回代办信息"
// @Failure      500  {string}  bool "获取失败"
// @Router       /auth/finished/todos [get]
func GetTodosFinished(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.GetTodosFinishedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.TodoResponse{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	todos, total := ts.GetFinishedTodos(uid.(uint64), int(req.PageNum), int(req.PageSize))

	var todoMaps []*todo.Todo
	for _, t := range todos {
		todoMaps = append(todoMaps, &todo.Todo{
			Id:        t.ID,
			Title:     t.Title,
			Content:   t.Content,
			View:      t.View,
			Status:    uint32(t.Status),
			CreatedAt: t.CreatedAt.Format(time.RFC3339),
			StartTime: t.StartTime.Format(time.RFC3339),
			EndTime:   t.EndTime.Format(time.RFC3339),
		})
	}

	c.JSON(consts.StatusCreated, &todo.TodoResponse{
		Status: 201,
		Msg:    "获取成功",
		Data: &todo.TodoList{
			Items: todoMaps,
			Total: total,
		},
	})
}

// @Summary      获取全部未完成代办
// @Description  用户获取他的全部未完成代办事件
// @Tags		 Todo
// @Produce      json
// @Success      200  {object}  []interface{} "返回代办信息"
// @Failure      500  {string}  bool "获取失败"
// @Router       /auth/notfinished/todos [get]
func GetTodosNotFinished(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.GetTodosNotFinishedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	todos, total := ts.GetNotFinishedTodos(uid.(uint64), int(req.PageNum), int(req.PageSize))

	var todoMaps []*todo.Todo
	for _, t := range todos {
		todoMaps = append(todoMaps, &todo.Todo{
			Id:        t.ID,
			Title:     t.Title,
			Content:   t.Content,
			View:      t.View,
			Status:    uint32(t.Status),
			CreatedAt: t.CreatedAt.Format(time.RFC3339),
			StartTime: t.StartTime.Format(time.RFC3339),
			EndTime:   t.EndTime.Format(time.RFC3339),
		})
	}

	c.JSON(consts.StatusCreated, &todo.TodoResponse{
		Status: 201,
		Msg:    "获取成功",
		Data: &todo.TodoList{
			Items: todoMaps,
			Total: total,
		},
	})
}

// @Summary      模糊查询代办
// @Description  用户根据关键字获取他的代办事件
// @Tags		 Todo
// @Produce      json
// @Success      200  {object}  []interface{} "返回代办信息"
// @Failure      500  {string}  bool "获取失败"
// @Router       /auth/key/todos [get]
func GetKeyTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.GetKeyTodosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.TodoResponse{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	todos, total := ts.GetTodosByKey(uid.(uint64), req.Key, int(req.PageNum), int(req.PageSize))

	var todoMaps []*todo.Todo
	for _, t := range todos {
		todoMaps = append(todoMaps, &todo.Todo{
			Id:        t.ID,
			Title:     t.Title,
			Content:   t.Content,
			View:      t.View,
			Status:    uint32(t.Status),
			CreatedAt: t.CreatedAt.Format(time.RFC3339),
			StartTime: t.StartTime.Format(time.RFC3339),
			EndTime:   t.EndTime.Format(time.RFC3339),
		})
	}

	c.JSON(consts.StatusCreated, &todo.TodoResponse{
		Status: 201,
		Msg:    "获取成功",
		Data: &todo.TodoList{
			Items: todoMaps,
			Total: total,
		},
	})
}

// @Summary      删除代办
// @Description  用户删除他的一个代办事件
// @Tags		 Todo
// @Produce      json
// @Success      204  {string}  bool "删除成功"
// @Failure      500  {string}  bool "删除失败"
// @Router       /auth/todo [delete]
func DeleteTodo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.DeleteTodoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}

	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.DeleteTodoById(req.Id, uid.(uint64)) {
		c.JSON(consts.StatusNoContent, &todo.Response{
			Status: 204,
			Msg:    "删除成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "删除失败",
	})
}

// @Summary      删除全部代办
// @Description  用户删除他的全部代办事件
// @Tags		 Todo
// @Produce      json
// @Success      204  {string}  bool "删除成功"
// @Failure      500  {string}  bool "删除失败"
// @Router       /auth/todos [delete]
func DeleteTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.DeleteTodosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.DeleteAll(uid.(uint64)) {
		c.JSON(consts.StatusNoContent, &todo.Response{
			Status: 204,
			Msg:    "删除成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "删除失败",
	})
}

// @Summary      删除全部完成代办
// @Description  用户删除他的全部完成代办事件
// @Tags		 Todo
// @Produce      json
// @Success      204  {string}  bool "删除成功"
// @Failure      500  {string}  bool "删除失败"
// @Router       /auth/finished/todo [delete]
func DeleteFinishedTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.DeleteFinishedTodosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.DeleteFinishedTodo(uid.(uint64)) {
		c.JSON(consts.StatusNoContent, &todo.Response{
			Status: 204,
			Msg:    "删除成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "删除失败",
	})
}

// @Summary      删除未完成代办
// @Description  用户删除他的全部未完成代办事件
// @Tags			 Todo
// @Produce      json
// @Success      204  {string}  bool "删除成功"
// @Failure      500  {string}  bool "删除失败"
// @Router       /auth/notfinished/todo [delete]
func DeleteNotFinishedTodos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req todo.DeleteNotFinishedTodosRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &todo.Response{
			Status: 400,
			Msg:    "参数错误",
		})
		return
	}
	uid, ok := c.Get("uid")
	if !ok {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{
			"status": 500,
			"msg":    "token过期",
		})
		return
	}
	ts := service.NewTodoService(repository.NewTodoRepository(database.GetMysql(), database.GetRedis()))
	if ts.DeleteNotFinishedTodo(uid.(uint64)) {
		c.JSON(consts.StatusNoContent, &todo.Response{
			Status: 204,
			Msg:    "删除成功",
		})
		return
	}

	c.JSON(consts.StatusInternalServerError, &todo.Response{
		Status: 500,
		Msg:    "删除失败",
	})
}
