// Code generated by hertz generator.

package main

import (
	"Demo/biz/dal"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	dal.Init()
	fmt.Println("init success")
}

func main() {
	Init()

	h := server.Default()

	register(h)
	h.Spin()
}
