// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebyscopeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchtodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todos0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateallstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7bid_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetodostatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}
