// Code generated by hertz generator.

package api

import (
	"memogo/pkg/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletebyscopeMw() []app.HandlerFunc {
	// 需要 JWT 认证
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func _todosMw() []app.HandlerFunc {
	// 需要 JWT 认证
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func _listtodosMw() []app.HandlerFunc {
	// 需要 JWT 认证
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func _deleteoneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchtodosMw() []app.HandlerFunc {
	// 需要 JWT 认证（组已包含，此处保持一致）
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func _todos0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodoMw() []app.HandlerFunc {
	// 需要 JWT 认证
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func _updateallstatusMw() []app.HandlerFunc {
	// 需要 JWT 认证
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func __7bid_7dMw() []app.HandlerFunc {
	// 需要 JWT 认证
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func _updatetodostatusMw() []app.HandlerFunc {
	// 需要 JWT 认证
	return []app.HandlerFunc{middleware.JWTMiddleware.MiddlewareFunc()}
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtodoscursorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchtodoscursorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}
