// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	todo "hertz/biz/router/todo"
	user "hertz/biz/router/user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	todo.Register(r)

	user.Register(r)
}
